version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-movies
    env_file:
        - .env
    volumes: 
      - ".:/app"
    ports:
      - "3001:3000"
    tty: true